name: Meowth Ci
on: 
  push:
    paths: 
      - client/src/*
    branches: 
      - master

jobs:
  jobs1:
    name: meowth-install
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: echo node -v
    
