name: update github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          node-version: "10.x"

      - name: Git Clone
        uses: actions/checkout@master

      - name: Install Dependencies
        run: cd client && npm install && cd ..

      - name: Ng Build
        run: |
          pwd
          npm run publish:client

      - name: Git Init
        run: |
          pwd
          cd ./client/dist
          git init
      - name: Git Commit
        run: |
          ls
          cd ./client/dist
          git add .
          git config user.email "${GITHUB_USER_EMAIL}"
          git config user.name "${GITHUB_USER}"
          git commit -m "update github pages"
      - name: Git Push
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_USER_EMAIL: ${{ secrets.GITHUB_USER_EMAIL }}
          ACCESS_TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
        run: |
          cd ./client/dist
          git push --set-upstream --force --quiet "https://${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master:gh-pages
